const truthQuestions = [
    "Jelaskan perbedaan kata baku dan tidak baku, lalu beri masing-masing 2 contoh yang berkaitan dengan kesehatan.",
    "Ceritakan kembali informasi tentang kesehatan yang pernah kamu baca atau dengar dalam waktu 1 menit.",
    "Sebutkan 5 kata yang berkaitan dengan kesehatan, lalu jelaskan arti salah satunya.",
    "Menurutmu, mengapa membaca informasi tentang kesehatan dapat menambah wawasan?",
    "Buat satu paragraf (4–5 kalimat) tentang pentingnya menjaga kesehatan secara lisan.",
    "Sebutkan 5 kata yang menggunakan awalan ber- dan berkaitan dengan kegiatan menjaga kesehatan.",
    "Apa perbedaan fakta dan opini? Berikan masing-masing satu contoh tentang kesehatan.",
    "Jika kamu menjadi penulis buku tentang kesehatan, topik apa yang akan kamu pilih? Jelaskan alasannya.",
    "Sebutkan minimal 3 kata hubung, lalu buat kalimat bertema kesehatan menggunakan masing-masing.",
    "Ceritakan kembali sebuah informasi tentang kesehatan dengan urutan yang runtut.",
    "Apa perbedaan kata benda, kata kerja, dan kata sifat? Berikan masing-masing 2 contoh bertema kesehatan.",
    "Sebutkan 5 kata yang menggunakan awalan me-, lalu buat satu kalimat bertema kesehatan dari salah satunya.",
    "Sebutkan 3 contoh sinonim dan 3 contoh antonim yang berkaitan dengan kesehatan.",
    "Mengapa penggunaan tanda baca penting dalam menulis informasi tentang kesehatan?",
    "Apa perbedaan kalimat tanya, kalimat perintah, dan kalimat berita? Berikan contoh bertema kesehatan.",
    "Menurutmu, apa ciri-ciri teks tentang kesehatan yang menarik dan mudah dipahami?",
    "Apa perbedaan informasi yang berupa fakta dan informasi yang berupa pendapat dalam teks kesehatan?",
    "Sebutkan 5 kata yang berkaitan dengan kesehatan, lalu gunakan salah satunya dalam sebuah kalimat.",
    "Apa yang harus diperhatikan ketika seseorang mendeskripsikan makanan atau minuman?",
    "Jika kamu membaca informasi kesehatan yang belum kamu pahami, informasi apa saja yang perlu kamu cari tahu?",
    "Mengapa sebuah teks tentang cara menjaga kesehatan harus memiliki urutan langkah yang jelas?",
    "Menurutmu, apa yang membuat seseorang menjadi pembicara yang baik ketika menyampaikan informasi kesehatan?",
    "Berikan pendapat tentang pentingnya menjaga kebersihan, lalu berikan 2 alasan yang mendukung pendapatmu.",
    "Sebutkan 5 kata yang berkaitan dengan pola hidup sehat, lalu buat kalimat menggunakan salah satunya.",
    "Pilih dua makanan atau minuman, lalu jelaskan perbedaannya menggunakan minimal 5 kalimat.",
    "Buat satu kalimat dengan 3 kesalahan tata bahasa bertema kesehatan, lalu temukan dan perbaiki semua kesalahan tersebut."
];


const dareQuestions = [
    "Buat cerita spontan dari tiga kata: sehat – sekolah – olahraga.",
    "Berpidato tentang pentingnya menjaga kesehatan selama 1 menit tanpa berhenti.",
    "Buat pantun bertema kesehatan.",
    "Sebutkan sebuah peribahasa yang kamu ketahui, lalu jelaskan artinya.",
    "Sebutkan sinonim dari 5 kata bertema kesehatan yang kamu pilih sendiri.",
    "Sebutkan antonim dari 5 kata yang kamu pilih sendiri dan buat semuanya berkaitan dengan kesehatan.",
    "Menjadi reporter yang sedang meliput kegiatan olahraga atau pemeriksaan kesehatan selama 1 menit.",
    "Ambil satu benda di kelas yang berkaitan dengan kesehatan atau kebersihan, lalu deskripsikan bentuk, warna, ukuran, bahan, dan kegunaannya tanpa menyebut nama benda tersebut.",
    "Amati sebuah benda yang berkaitan dengan kesehatan selama 10 detik, kemudian sebutkan minimal 5 cirinya.",
    "Pilih sebuah benda yang berkaitan dengan kesehatan dan jelaskan cirinya tanpa menyebut nama dan fungsinya. Teman harus menebaknya.",
    "Buat satu kalimat menggunakan kata karena, tetapi, dan sehingga dengan tema kesehatan.",
    "Buat satu kalimat yang memiliki kata benda, kata kerja, dan kata sifat dengan tema kesehatan.",
    "Buat sebuah kalimat tentang kesehatan yang salah, lalu perbaiki kalimat tersebut dan jelaskan kesalahannya.",
    "Ubah sebuah kalimat aktif bertema kesehatan menjadi kalimat pasif.",
    "Ubah sebuah kalimat pasif bertema kesehatan menjadi kalimat aktif.",
    "Buat sebuah kalimat tanya tentang kesehatan, kemudian ubah menjadi kalimat berita.",
    "Buat sebuah kalimat perintah untuk menjaga kesehatan yang terdengar sopan.",
    "Buat paragraf pendek tentang kebiasaan hidup sehat dengan minimal 4 kalimat yang saling berhubungan.",
    "Amati keadaan di sekitarmu, lalu sebutkan 3 fakta dan 1 opini berdasarkan pengamatan tentang kesehatan atau kebersihan.",
    "Buat cerita pendek menggunakan 4 kata bertema kesehatan yang kamu pilih sendiri.",
    "Jelaskan sebuah kebiasaan sehat selama 30 detik tanpa menggunakan kata \"eee\", \"anu\", atau \"apa ya\".",
    "Buat sebuah kalimat bertema kesehatan yang terdiri dari minimal 10 kata dan tetap memiliki makna yang jelas.",
    "Baca sebuah kalimat tentang kesehatan dengan intonasi seperti seorang pembawa berita.",
    "Buat sebuah pantun yang memiliki tema kesehatan, kebersihan, atau olahraga.",
    "Ceritakan pengalaman yang berkaitan dengan menjaga kesehatan dengan urutan awal, kejadian, dan akhir.",
    "Pilih satu kebiasaan sehat, lalu bandingkan kebiasaan tersebut dengan kebiasaan yang kurang sehat menggunakan minimal 3 kata sifat.",
    "Buat deskripsi sebuah benda yang berkaitan dengan kesehatan sehingga teman dapat menebaknya hanya berdasarkan penjelasanmu.",
    "Jelaskan sebuah kebiasaan sehat selama 1 menit tanpa menyebut nama kebiasaan, manfaat, maupun contohnya.",
    "Buat cerita yang harus memuat 5 kata bertema kesehatan yang kamu pilih sendiri.",
    "Bercerita selama 1 menit tentang hidup sehat tanpa mengucapkan kata \"dan\".",
    "Sebutkan kata secara bergantian sesuai kategori: kata benda → kata kerja → kata sifat. Gunakan tema kesehatan. Berhenti lebih dari 3 detik = kalah.",
    "Debat singkat selama 30 detik tentang topik: \"Olahraga pagi lebih baik daripada olahraga malam.\"",
    "Buat satu paragraf tentang kesehatan yang memiliki kalimat utama dan minimal 3 kalimat penjelas secara lisan.",
    "Amati sebuah benda selama 15 detik, kemudian deskripsikan benda tersebut tanpa melihatnya lagi.",
    "Buat cerita spontan dari 5 kata bertema kesehatan yang kamu pilih sendiri dan tidak berhubungan satu sama lain.",
    "Buat sebuah cerita tentang seseorang yang ingin hidup sehat dan harus memiliki awal, konflik, dan penyelesaian dalam waktu 1 menit.",
    "Pilih 5 kata bertema kesehatan secara acak, lalu susun semuanya menjadi kalimat yang benar tanpa menambahkan kata lain.",
    "Buat satu paragraf tentang pola hidup sehat yang memiliki kata hubung, kata sifat, kata kerja, dan kata benda.",
    "Deskripsikan sebuah benda yang berkaitan dengan kesehatan tanpa menyebut nama, warna, bentuk, dan fungsi benda tersebut. Teman harus tetap bisa menebaknya.",
    "Ceritakan sebuah kejadian tentang kesehatan selama 1 menit dengan urutan yang runtut dan tanpa mengulang kalimat yang sama.",
    "Buat sebuah kalimat bertema kesehatan, kemudian teman harus menentukan subjek, predikat, objek, dan keterangannya."
];